global:
  servicename: DOCGILITY-TEST

app:
  servicename: Docgility-Test
  smtpusername: TBD
  smtpsendasemail: TBD
  smtppassword: TBD
  smtphostname: TBD
  smtpport: 587
  norequireauthemail: TRU

saml:
  activated: FAL
  idpentityid: TBD
  idpsinglesignonserviceurl: TBD
  idpx509cert: TBD
