global:
  servicename: E Corp
  appssologin: FAL
  appurl: willbeoverwritten
  
app:
  servicename: E Corp

  # VCN
  vcnenabled: TRU
  vcnaddress: http://vcntest.docgility.com
  vcnverifiedemailsuffixes: e.com
  vcnsourceid: M11
  vcnsourcekey: M11key
  vcnsecuritykeys: NONE
  vcndestkeys: M11key1,M11key2,M11key3

  integ1name: AzureOpenAIInteg
  integ1type: integAzureOpenAI
  integ1creds: 2024-05-01-preview,4EF8yZQR7fsqZbB2UQ9NiTxcBRlgPXNAO8XaSCbKkLk181lK5OdGJQQJ99BDACYeBjFXJ3w3AAABACOGprJK
  integ1specs: https://docg.openai.azure.com/,gpt-4o-mini
  integ1paras: Formalize in legal language and make the terms,better for originating party,better for counter party,less overall risk,DG(testdemo)

  smtpusername: not@docgility.com
  smtpsendasemail: not@docgility.com
  smtppassword: xxxxxxxx
  smtphostname: smtp.gmail.com
  smtpport: 587
  norequireauthemail: TRU
  
saml:
  # Example of deactivated SSO Settings
  activated: FAL
  idpentityid: TBD
  idpsinglesignonserviceurl: TBD
  idpx509cert: TBD