global:
  servicename: E Corp
  appssologin: FAL
  
app:
  servicename: E Corp

  # HUB
  vcnenabled: TRU
  vcnaddress: http://vcntest.docgility.com
  vcnverifiedemailsuffixes: e.com
  vcnsourceid: M11
  vcnsourcekey: M11key
  vcnsecuritykeys: NONE
  vcndestkeys: M11key1,M11key2,M11key3

  smtpusername: not@docgility.com
  smtpsendasemail: not@docgility.com
  smtppassword: xxxxxxxx
  smtphostname: smtp.gmail.com
  smtpport: 587
  norequireauthemail: TRU
  
saml:
  # Example of deactivated SSO Settings
  activated: FAL
  idpentityid: TBD
  idpsinglesignonserviceurl: TBD
  idpx509cert: TBD