
global:
  servicename: C CORP - SELLER
  appssologin: FAL
  
app:
  servicename: C CORP - SELLER

  # HUB
  vcnenabled: TRU
  vcnaddress: http://vcntest.docgility.com
  vcnverifiedemailsuffixes: c.com
  vcnsourceid: H11
  vcnsourcekey: H11key
  vcnsecuritykeys: NONE
  vcndestkeys: H11key1,H11key2,H11key3

  smtpusername: not@docgility.com
  smtpsendasemail: not@docgility.com
  smtppassword: xxxxxxxx
  smtphostname: smtp.gmail.com
  smtpport: 587
  norequireauthemail: TRU
  
saml:
  # Example of deactivated SSO Settings
  activated: FAL
  idpentityid: TBD
  idpsinglesignonserviceurl: TBD
  idpx509cert: TBD
