global:
  servicename: B LAW - ATTORNEY
  appssologin: FAL
  
app:
  servicename: B LAW - ATTORNEY

  # VCN
  vcnenabled: TRU
  vcnaddress: http://vcntest.docgility.com
  vcnverifiedemailsuffixes: b.com
  vcnsourceid: G11
  vcnsourcekey: G11key
  vcnsecuritykeys: NONE
  vcndestkeys: G11key1,G11key2,G11key3

  smtpusername: not@docgility.com
  smtpsendasemail: not@docgility.com
  smtppassword: xxxxxxxx
  smtphostname: smtp.gmail.com
  smtpport: 587
  norequireauthemail: TRU
  
saml:
  # Example of deactivated SSO Settings
  activated: FAL
  idpentityid: TBD
  idpsinglesignonserviceurl: TBD
  idpx509cert: TBD
