global:
  servicename: D LAW - ATTORNEY
  appssologin: FAL
  
app:
  servicename: D LAW - ATTORNEY

  # VCN
  vcnenabled: TRU
  vcnaddress: http://vcntest.docgility.com
  vcnverifiedemailsuffixes: d.com
  vcnsourceid: L11
  vcnsourcekey: L11key
  vcnsecuritykeys: NONE
  vcndestkeys: L11key1,L11key2,L11key3

  smtpusername: not@docgility.com
  smtpsendasemail: not@docgility.com
  smtppassword: xxxxxxxx
  smtphostname: smtp.gmail.com
  smtpport: 587
  norequireauthemail: TRU
  
saml:
  # Example of deactivated SSO Settings
  activated: FAL
  idpentityid: TBD
  idpsinglesignonserviceurl: TBD
  idpx509cert: TBD