global:
  servicename: DOCGILITY-TEST
  # replace below with the urls for each of the services exposed via app gateway.
  beurl: http://20.38.169.237:8000
  beaiurl: http://20.38.169.237:8001
  appurl: http://20.38.169.237
  appssologin: TRU

app:
  servicename: DOCGILITY-TEST

  smtpusername: not@docgility.com
  smtpsendasemail: not@docgility.com
  smtppassword: xxxxxxxx
  smtphostname: smtp.gmail.com
  smtpport: 587
  # set to TRU if you want to disable requiring email verification for new registrants.
  # Should be TRU for testing, but FAL for production
  norequireauthemail: TRU

  # example format - this format works (values are obscured for security)
  # smtpusername: XXXXXXXX@docgility.com
  # smtpsendasemail: XXXXXXXX@docgility.com
  # smtppassword: XXXXXX
  # smtphostname: smtp.gmail.com
  # smtpport: 587
  # norequireauthemail: TRU

  # overrides for HUB
  # constants for hub >3.3.0
  
  # hubenabled: TRU
  # hubaddress: http://host.docker.internal:8050
  # hubverifiedemailsuffixes: '@docgility.com'
  # hubsourceid: 11212
  # hubsourcekey: 456
  # hubsecuritykeys: NONE
  # hubdestkeys: A123,A456,A789

  # synctimeinstance: 5s
  # synctimehub: 100s

  # SMTP Settings are required if email registrations are accepted.  Otherwise, SSO is required to login (see below).

  # constants for vcn >3.3.0
  vcnenabled: TRU
  vcnaddress: http://host.docker.internal:8050
  vcnverifiedemailsuffixes: docgility.com
  vcnpushupdates: TRU
  vcnsourceid: A1212
  vcnsourcekey: AB456
  vcnsecuritykeys: NONE
  vcndestkeys: A123,A456,A789

  synctimeinstance: 5s
  synctimevcn: 10s

  # Adding constants for Docgility >4.1
  # appbeaiaddress: http://host.docker.internal:8061
  appdocgtitleenv: DOCGILITY
  appnorequireauthemail: TRU
  appinstancetype: ENTERPRISE

  integ1name: AzureOpenAIInteg
  integ1type: integAzureOpenAI
  integ1creds: 2024-05-01-preview,4EF8yZQR7fsqZbB2UQ9NiTxcBRlgPXNAO8XaSCbKkLk181lK5OdGJQQJ99BDACYeBjFXJ3w3AAABACOGprJK
  integ1specs: https://docg.openai.azure.com/,gpt-4o-mini
  integ1paras: Formalize in legal language and make the terms,better for originating party,better for counter party,less overall risk,DG(testdemo)

  integ2name: INTEG2NAME-TEST
  integ2type: integTYPE3
  integ2creds: INTEG2CREDS-TEST
  integ2specs: INTEG2PARAS-TEST
  integ2paras: INTEG2SPECS-TEST

  integ3name:
  integ3type:
  integ3creds:
  integ3specs:
  integ3paras:

  integ4name:
  integ4type:
  integ4creds:
  integ4specs:
  integ4paras:




saml:
  # Example of deactivated SSO Settings
  # activated: FAL
  # idpentityid: TBD
  # idpsinglesignonserviceurl: TBD
  # idpx509cert: TBD

  # Example of an activated SSO Setting - using Okta trial account
  activated: TRU
  idpentityid: http://www.okta.com/exk95lumj0UJK3bEO4x7
  idpsinglesignonserviceurl: https://dev-376038.okta.com/app/dev-376038_docgility_1/exk95lumj0UJK3bEO4x7/sso/saml
  idpx509cert: MIIDpDCCAoygAwIBAgIGAYM9UMuEMA0GCSqGSIb3DQEBCwUAMIGSMQswCQYDVQQGEwJVUzETMBEGA1UECAwKQ2FsaWZvcm5pYTEWMBQGA1UEBwwNU2FuIEZyYW5jaXNjbzENMAsGA1UECgwET2t0YTEMBIGA1UECwwLU1NPUHJvdmlkZXIxEzARBgNVBAMMCmRldi0zNzYwMzgxHDAaBgkqhkiG9w0BCQEWDWluZm9Ab2t0YS5jb20wHhcNMjIwOTE0MTg0MzA4WhcNMzIwOTE0MTg0NDA4WjCBkjELMAkGA1UBhMCVVMxEzARBgNVBAgMCkNhbGlmb3JuaWExFjAUBgNVBAcMDVNhbiBGcmFuY2lzY28xDTALBgNVBAoMBE9rdGExFDASBgNVBAsMC1NTT1Byb3ZpZGVyMRMwEQYDVQQDDApkZXYtMzc2MDM4MRwwGgYJKoZIhvcNAQkBFg1pbmZvQG9rdGEuY29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnbtCjCC2H/0tRROIV/kz60w2aOqQH664YoGgBWXr4cviKn6KmsnOfAMagszfhWmghQJGmb7z7PTGeZQshH/MvjvdD9gBLhHqAwn0cTFm8CiSiVkDUxn3gRISJ8WijAvj2GLL1qMRU3r33m0gIYTm+ZVH4i09xQkDFg4jcRzP2G4xWTbraDfKHh8DQRUVQAiUz8RM4oHVdfr7emhwy2kGonZFq6vKEfwjvxJBmEBVqE5HL2YPKRBY/+VXWOU9JDlS0/keIBPuLsS1X7fu26CmWzU/f+59rLc8xpnJRUI/BZaw2tg644KNXrqaEBz8Xvt8L/gUN8ArdiHy9D9H3QsIKQIDAQABMA0GCSqGSIb3DQEBCwUAA4IBAQBHCQjBlYblCdAnOtZ34byyn0EjUeaDYLbPjX4o3kWn88QWsxuCBItN27G4UJ2ydyL2eGAK5SB+G0uIx9K+MDN4i7Ul+4uCErGot03moBSN6RVY685u53dsxNnnyNVF9AOFgBJjrcFeRc/wtBX9+fqDmsaT8yRei7TuF+jZBfbunXVo5qUGZ4FE0yG36fhargYpoLDd5j1gTR6RvnufxPjZIhT3Pgasx18B60Y6cWGwG6tsoGvBHwE5/FPvszBgD49Crvr2jg091h8rh9aRY53p8KTn7J6OWvJ3xPFeMdZEDQRfVrIAfiyIiH25h6SPALe4W/a7+6ixxojZnDdWL6jn
