
global:
  servicename: C CORP - SELLER
  appssologin: FAL
  
app:
  servicename: C CORP - SELLER

  # HUB
  hubenabled: TRU
  hubaddress: http://13.90.147.57
  hubverifiedemailsuffixes: c.com
  hubsourceid: H11
  hubsourcekey: H11key
  hubsecuritykeys: NONE
  hubdestkeys: H11key1,H11key2,H11key3

  smtpusername: not@docgility.com
  smtpsendasemail: not@docgility.com
  smtppassword: xxxxxxxx
  smtphostname: smtp.gmail.com
  smtpport: 587
  norequireauthemail: TRU
  
saml:
  # Example of deactivated SSO Settings
  activated: FAL
  idpentityid: TBD
  idpsinglesignonserviceurl: TBD
  idpx509cert: TBD
